### ISSUE TITLE
Near term to-do list

### ISSUE THREAD

**Issue by mcclearyj** [mcclearyj/cweb_psf#2]
To make this codebase more useful for the rest of the collaboration as an independent PSF fitting and diagnostic tool, the following tasks need to be completed. This list will be updated as we proceed and new scripts get added. 

- [x] Add capability to use external reference star catalog for PSF fitting in  [get_jwst_psf.py](https://github.com/mcclearyj/cweb_psf/blob/034a6ddf82fec811b5c955937f187e6201681262/get_jwst_psf.py)
- [ ] Add a decorator to PIFF models that adds the PSFEx functionality required by Sextractor++ 
- [x] Run PSFEx model in [get_jwst_psf.py](https://github.com/mcclearyj/cweb_psf/blob/034a6ddf82fec811b5c955937f187e6201681262/get_jwst_psf.py) 
- [x] Remove hard-coded image names!
- [x] Turn this hard-coded star selection function into a configuration file that can be adapted for other data and passed to the PSF fitting code. Useful for cases where a reference catalog is not provided. 
- [x] Make PIFF auto-star selection work
- [ ] Possibly turn [this loop](https://github.com/mcclearyj/cweb_psf/blob/034a6ddf82fec811b5c955937f187e6201681262/get_jwst_psf.py#L238) into a class, especially since variables get passed back and forth between functions. Perhaps not strictly necessary, but would clean up code a bit. 
- [x] Push PSF data products to Candide for others to use
- [x] Add Tobias Liaudat tools?

**Comment by mcclearyj** [comment]
Subsumed into issue #10
